### PR TITLE
Changed height of nav div to h-fit

### LINKED ISSUE #63: Add space between bottom of main nav panel and bottom of viewport
### Enhancement Description

The site navigation has been overhauled but one shortcoming is that on smaller desktop screens it will extend beyond the bottom of the viewport:
Screenshot of main navigation panel

It would be a better experience for the user if the panel always left some space between it, and the bottom of the viewport, so that there is a generous "click-away" area to close the navigation. Any overflowing content should be scrollable along the y-axis within the navigation container:
Main navigation page with space

### Additional Context

The Apple site is a good example of the kind of implementation we're after:
Screenshot of nav on Apple.com adjusting to viewport height

### Acceptance Criteria

- There should always be a gap of approx 8rem between the bottom of the navigation panel and the bottom of the viewport
- As our navigation is full-screen on smaller viewports, this change should only be applied at `lg`
- Navigation panel content should scroll on the y-axis if it overflows

### Suggested Solution

_No response_

### PR DESCRIPTION
**Pull request by aditya000028**
#### Changes:
- changed height of navigation div from `lg:h-[800px]` to `lg:h-fit`

image

I realize that this change does not specifically create `8rem` space as requested, but I think this may be a cleaner solution to the problem while still ensuring there is enough click away space at the bottom. Let me know what you think!

#### Changes
- changed the width of site header from `w-screen` to `w-full` to remove unnecessary horizontal scrollbar
- made height of nav panel take only 75% of the viewport height

image

Closes #63

### CODE REVIEW

**Review by danlechambre — CHANGES_REQUESTED** [review]
Hey @aditya000028 it's great to have another dev aboard 😃 

Let's get into this 🤜🤛

Unfortunately `h-fit` is poorly supported in Safari. It gets rendered with a height of 0:
CleanShot 2024-11-08 at 19 16 28@2x

I _think_ the problem here is that the parent uses CSS grid and/or the element is absolutely positioned so has no intrinsic height. As such dynamic properties like `h-fit`, `h-auto` etc. will cause the height to collapse to 0

I'd recommend looking into doing this with something like `calc()` maybe something like `h-[calc(100vh-headerHeight-spaceAtBottom)]` might work. Where `headerHeight` and `spaceAtBottom` are calculated or rough arbitrary values to give us that ideal spacing at the bottom.

I think it would be great if we can maintain a consistent height and bottom spacing for all panels so it is less jarring when the user switches between them.

I think another issue with `h-fit` might be that the panel height will always fit the content- meaning that we'll still end up extending beyond the bottom of the viewport if the browser window height is small resulting in content the user can't get to

Reach out if you have any trouble

**Comment by aditya000028** [comment]
Hi @danlechambre , excited to be on the team!

Sorry I did not test the previous changes on multiple browsers. 

I previously thought about using `calc` as well, but I think the new changes that I just pushed would work just as well and keep a cleaner code. It would reduce the client work as we would have to write a JavaScript script (a short one, but still). I changed the height of the nav panel to cover 75% of the viewport height, ensuring there is always enough space to click away on `lg` screens. 
Let me know if you still would like to go with the `calc` method. When I was playing around with that method though while using something like `calc(100vh-8rem)`, I noticed that `8rem` was not cutting it. There was still no space for the user to click away. There was noticeable changes when I changed the `8rem` value to about 12-14.

Additionally, I made a small change to the site header. Previously, the header value was creating an unnecessary horizontal scrollbar because of the width of the header. I changed it from `w-screen` to `w-full`

Let me know what you think of the changes!

**Review by danlechambre — APPROVED** [review]
This approach works ok up to about 640px browser window - which I think is fine for now. You're absolutely correct in that adding client script would be overkill. I think an easy solution may have been to use dev tools to grab the header height and then find a rem value that gave a nice buffer at most window sizes, something like: 
`lg:h-[calc(100vh-6rem-128px)]` 

Honestly, the solution you've implemented seems fine and solves the main issue of scrolling issues, happy to merge 😊

**Comment by aditya000028** [comment]
Awesome, thanks for your review! We can revisit the issue again in the future if it is still causing problems.

**Pull request merged**
